---
application:
  name: "discord-bot"
  project: "discord-bot"
  organization: "QoveryCommunity"
routers:
- name: "main-discord-bot"
  routes:
  - application_name: "discord-bot"
    paths:
    - "/*"
